
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'nl' | 'fr';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const defaultLanguage: Language = 'en';

const LanguageContext = createContext<LanguageContextType>({
  language: defaultLanguage,
  setLanguage: () => {},
  t: (key: string) => key,
});

// Translations object
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'app.name': 'InvoiceFlow Genius',
    'login': 'Login',
    'register': 'Register',
    'logout': 'Logout',
    'free.version': 'Free Version',
    'contact': 'Contact',
    'pricing': 'Pricing',
    'loading': 'Loading...',
    'view.all': 'View All',
    'dashboard': 'Dashboard',
    'welcome.back': 'Welcome back to your dashboard',
    'error': 'Error',
    'success': 'Success',
    'total.invoices': 'Total Invoices',
    'pending.amount': 'Pending Amount',
    'total.clients': 'Total Clients',
    'revenue.growth': 'Revenue Growth',
    'from.last.month': 'from last month',
    'new.this.month': 'new this month',
    'year.over.year': 'year over year',
    'increase': 'increase',
    'decrease': 'decrease',
    'create': 'Create',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'search': 'Search',
    'all_invoices': 'All Invoices',
    'invoice_number': 'Invoice #',
    'client_information': 'Client Information',
    'select_client': 'Select Client',
    'line_items': 'Line Items',
    'profile_created': 'New profile created successfully',
    'profile_updated': 'Profile updated successfully',
    'failed_to_fetch_profile_data': 'Failed to fetch profile data',
    'failed_to_create_profile': 'Failed to create new profile',
    'failed_to_update_profile': 'Failed to update profile',
    'business_settings_updated': 'Business settings updated successfully',
    'failed_to_fetch_business_data': 'Failed to fetch business data',
    'failed_to_update_business_settings': 'Failed to update business settings',
    'notes_attachments': 'Notes & Attachments',
    'payment_information': 'Payment Information',
    'payment_terms': 'Payment Terms',
    'po_number': 'PO Number',
    'qty': 'Quantity',
    'quantity': 'Quantity',
    'unit_price': 'Unit Price',
    'unit_type': 'Unit Type',
    'vat_rate': 'VAT Rate',
    'vat_percent': 'VAT %',
    'discount': 'Discount',
    'subtotal': 'Subtotal',
    'total': 'Total',
    'save_invoice': 'Save Invoice',
    'create_invoice': 'Create Invoice',
    'update_invoice': 'Update Invoice',
    
    // Auth
    'auth.login.success': 'Login Successful',
    'auth.welcome.back': 'Welcome back to InvoiceFlow Genius!',
    'auth.login.failed': 'Login Failed',
    'auth.check.credentials': 'Failed to log in. Please check your credentials and try again.',
    'auth.signup.success': 'Signup Successful',
    'auth.verify.email': 'Welcome to InvoiceFlow Genius! Please check your email to verify your account.',
    'auth.signup.failed': 'Signup Failed',
    'auth.try.again': 'Failed to create account. Please try again.',
    'auth.have.account': 'Enter your credentials to access your account',
    'auth.no.account': 'Create a new account to get started',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.email.placeholder': 'your.email@example.com',
    'auth.password': 'Password',
    'auth.confirm.password': 'Confirm Password',
    'auth.logging.in': 'Logging in...',
    'auth.creating.account': 'Creating account...',
    'auth.password.mismatch': 'Passwords do not match',
    'auth.password.length': 'Password must be at least 6 characters',
    'auth.terms.agreement': 'By continuing, you agree to our Terms of Service and Privacy Policy.',
    
    // Navigation and sections
    'clients.title': 'Clients',
    'invoices.title': 'Invoices',
    'quotes.title': 'Quotes',
    'settings.title': 'Settings',
    'invoices': 'Invoices',
    'due_date': 'Due Date',
    'client': 'Client',
    'amount': 'Amount',
    'status': 'Status',
    'actions': 'Actions',
    'search_invoices': 'Search invoices...',
    'loading_invoices': 'Loading invoices...',
    'no_invoices_match_search': 'No invoices match your search',
    'no_invoices_found': 'No invoices found. Create your first invoice!',
    'download_pdf': 'Download PDF',
    'send_email': 'Send Email',
    'email': 'Email',
    'cancel_via_credit_note': 'Cancel via Credit Note',
    'duplicate': 'Duplicate',
    'delete_invoice': 'Delete Invoice',
    'delete_invoice_confirmation': 'Are you sure you want to delete invoice',
    'this_action_cannot_be_undone': 'This action cannot be undone.',
    'deleting': 'Deleting...',
    'invoice_deleted': 'Invoice Deleted',
    'invoice_deleted_description': 'The invoice has been successfully deleted.',
    'failed_to_delete_invoice': 'Failed to delete invoice',
    'invoice_updated': 'Invoice Updated',
    'invoice_status_updated': 'The invoice status has been updated.',
    'failed_to_update_invoice_status': 'Failed to update invoice status',
    'invoice_duplicated': 'Invoice Duplicated',
    'invoice_duplicated_description': 'A copy of the invoice has been created.',
    'failed_to_duplicate_invoice': 'Failed to duplicate invoice',
    'email_sent': 'Email Sent',
    'email_sent_description': 'The invoice has been emailed to',
    'generating_pdf': 'Generating PDF',
    'generating_pdf_description': 'Your invoice PDF is being prepared for download.',
    'date': 'Date',
    
    // Quotes
    'quotes.add': 'Add Quote',
    'quotes.all': 'All Quotes',
    'quotes.search': 'Search quotes...',
    'quotes.none_found': 'No quotes found. Create your first quote!',
    'quotes.no_match_search': 'No quotes match your search',
    'quotes.number': 'Quote #',
    'quotes.expiry_date': 'Expiry Date',
    'quotes.cancel': 'Cancel Quote',
    'quotes.delete': 'Delete Quote',
    'quotes.confirm_delete': 'Are you sure you want to delete quote',
    
    // Settings
    'settings.billing': 'Billing & Subscription',
    'settings.billing.manage': 'Manage your billing information and subscription details',
    'settings.billing.current.plan': 'Current Plan',
    'settings.billing.payment.methods': 'Payment Methods',
    'settings.billing.no.payment.methods': 'You haven\'t added any payment methods yet.',
    'settings.billing.add.payment': 'Add Payment Method',
    
    // Dashboard
    'dashboard.recent.activity': 'Recent Activity',
    'dashboard.invoice.overview': 'Invoice Overview',
    
    // Pricing
    'pricing.free': 'Free',
    'pricing.yearly': 'Yearly',
    'pricing.monthly': 'Monthly',
    'pricing.save.up.to': 'Save up to 20%',
    'pricing.starter': 'Starter',
    'pricing.standard': 'Standard',
    'pricing.pro': 'Pro',
    'pricing.per.month': 'per month',
    'pricing.month': 'month',
    'pricing.promo.starter': 'Promotion for small starters',
    'pricing.most.popular': 'Most popular option',
    'pricing.good.for.active': 'Good for high activity',
    'pricing.free.trial': 'Free trial',
    'pricing.tax.deductible': '100% tax deductible!',
    'pricing.invoices.per.quarter': 'invoices / quarter',
    'pricing.quotes.per.quarter': 'quotes / quarter',
    'pricing.free.access': 'Free access',
    'pricing.unlimited.users': 'Unlimited users',
    'pricing.user': 'user',
    'pricing.all.prices': '*All prices excl. 21% VAT.',
    'pricing.custom.price': 'For businesses with more than 900 invoices per quarter, we provide a personalized price.',
    'pricing.simple.transparent': 'Simple, Transparent Pricing',
    'pricing.choose.plan': 'Choose the plan that works best for your business',
    'pricing.individuals.small': 'For individuals and small businesses',
    'pricing.growing.businesses': 'For growing businesses',
    'pricing.companies.teams': 'For companies and teams',
    'pricing.unlimited.invoices': 'Unlimited Invoices',
    'pricing.unlimited.clients': 'Unlimited Clients',
    'pricing.pdf.export': 'PDF Export',
    'pricing.email.invoices': 'Email Invoices',
    'pricing.basic.analytics': 'Basic analytics',
    'pricing.advanced.analytics': 'Advanced analytics',
    'pricing.email.support': 'Email support',
    'pricing.priority.support': 'Priority support',
    'pricing.custom.branding': 'Custom branding',
    'pricing.multiple.users': 'Multiple users',
    'pricing.get.started': 'Get Started',
    'pricing.subscribe.now': 'Subscribe Now',
    'pricing.contact.sales': 'Contact Sales',
    'pricing.business': 'Business',
    
    // Settings continued
    'settings.company': 'Company',
    'settings.profile': 'Profile',
    'settings.users': 'Users',
    'settings.general': 'General',
    'settings.localization': 'Localization',
    'settings.email_settings': 'Email Settings',
    'settings.integrations': 'Integrations',
    'settings.customize_look': 'Customize Look',
    'settings.security': 'Security',
    'settings.api': 'API',
    'settings.developers': 'Developers',
    'settings.advanced': 'Advanced',
    'settings.my_profile': 'My Profile',
    'settings.edit_profile': 'Edit Profile',
    'settings.change_password': 'Change Password',
    'settings.notifications': 'Notifications',
    'settings.account_settings': 'Account Settings',
    'settings.plan_details': 'Plan Details',
    'settings.usage': 'Usage',
    'settings.invoices_and_billing': 'Invoices & Billing',
    'settings.payment_methods': 'Payment Methods',
    'settings.cancel_subscription': 'Cancel Subscription',
    'settings.company_profile': 'Company Profile',
    'settings.business_details': 'Business Details',
    'settings.tax_information': 'Tax Information',
    'settings.financial_details': 'Financial Details',
    'settings.email_templates': 'Email Templates',
    'settings.invoice_settings': 'Invoice Settings',
    'settings.quote_settings': 'Quote Settings',
    'settings.api_keys': 'API Keys',
    'settings.webhooks': 'Webhooks',
    'settings.audit_log': 'Audit Log',
    'settings.data_export': 'Data Export',
    'settings.gdpr_compliance': 'GDPR Compliance',
    'settings.terms_of_service': 'Terms of Service',
    'settings.privacy_policy': 'Privacy Policy',
    'settings.cookie_policy': 'Cookie Policy',
    'settings.licenses': 'Licenses',
    'settings.third_party_licenses': 'Third-Party Licenses',
    'settings.version': 'Version',
    'settings.release_notes': 'Release Notes',
    'settings.support': 'Support',
    'settings.documentation': 'Documentation',
    'settings.community_forum': 'Community Forum',
    'settings.tutorials': 'Tutorials',
    'settings.faq': 'FAQ',
    'settings.contact_us': 'Contact Us',
    'settings.feedback': 'Feedback',
    'settings.report_a_bug': 'Report a Bug',
    'settings.request_a_feature': 'Request a Feature',
    'settings.keyboard_shortcuts': 'Keyboard Shortcuts',
    'settings.accessibility': 'Accessibility',
    'settings.dark_mode': 'Dark Mode',
    'settings.language': 'Language',
    'settings.time_zone': 'Time Zone',
    'settings.date_format': 'Date Format',
    'settings.currency': 'Currency',
    'settings.country': 'Country',
    'settings.address': 'Address',
    'settings.city': 'City',
    'settings.state': 'State',
    'settings.zip_code': 'Zip Code',
    'settings.phone': 'Phone',
    'settings.website': 'Website',
    'settings.logo': 'Logo',
    'settings.social_media': 'Social Media',
    'settings.facebook': 'Facebook',
    'settings.twitter': 'Twitter',
    'settings.linkedin': 'LinkedIn',
    'settings.instagram': 'Instagram',
    'settings.youtube': 'YouTube',
    'settings.skype': 'Skype',
    'settings.slack': 'Slack',
    'settings.discord': 'Discord',
    'settings.telegram': 'Telegram',
    'settings.whatsapp': 'WhatsApp',
    'settings.wechat': 'WeChat',
    'settings.qq': 'QQ',
    'settings.weibo': 'Weibo',
    'settings.vk': 'VK',
    'settings.odnoklassniki': 'Odnoklassniki',
    'settings.tumblr': 'Tumblr',
    'settings.pinterest': 'Pinterest',
    'settings.flickr': 'Flickr',
    'settings.dribbble': 'Dribbble',
    'settings.behance': 'Behance',
    'settings.medium': 'Medium',
    'settings.github': 'GitHub',
    'settings.gitlab': 'GitLab',
    'settings.bitbucket': 'Bitbucket',
    'settings.stackoverflow': 'Stack Overflow',
    'settings.quora': 'Quora',
    'settings.reddit': 'Reddit',
    'settings.hacker_news': 'Hacker News',
    'settings.product_hunt': 'Product Hunt',
    'settings.crunchbase': 'Crunchbase',
    'settings.angelist': 'AngelList',
    'settings.glassdoor': 'Glassdoor',
    'settings.indeed': 'Indeed',
    'settings.monster': 'Monster',
    'settings.careerbuilder': 'CareerBuilder',
    'settings.dice': 'Dice',
    'settings.linkedin_jobs': 'LinkedIn Jobs',
    'settings.indeed_jobs': 'Indeed Jobs',
    'settings.monster_jobs': 'Monster Jobs',
    'settings.careerbuilder_jobs': 'CareerBuilder Jobs',
    'settings.dice_jobs': 'Dice Jobs',
    'settings.google_jobs': 'Google Jobs',
    'settings.bing_jobs': 'Bing Jobs',
    'settings.yahoo_jobs': 'Yahoo Jobs',
  },
  nl: {
    // Common
    'app.name': 'InvoiceFlow Genius',
    'login': 'Inloggen',
    'register': 'Registreren',
    'logout': 'Uitloggen',
    'free.version': 'Gratis Versie',
    'contact': 'Contact',
    'pricing': 'Prijs',
    'loading': 'Laden...',
    'view.all': 'Bekijk Alles',
    'dashboard': 'Dashboard',
    'welcome.back': 'Welkom terug bij uw dashboard',
    'error': 'Fout',
    'success': 'Succes',
    'total.invoices': 'Totaal Facturen',
    'pending.amount': 'Openstaand Bedrag',
    'total.clients': 'Totaal Klanten',
    'revenue.growth': 'Omzetgroei',
    'from.last.month': 'ten opzichte van vorige maand',
    'new.this.month': 'nieuw deze maand',
    'year.over.year': 'jaar op jaar',
    'increase': 'stijging',
    'decrease': 'daling',
    'create': 'Maken',
    'save': 'Opslaan',
    'cancel': 'Annuleren',
    'delete': 'Verwijderen',
    'edit': 'Bewerken',
    'search': 'Zoeken',
    'all_invoices': 'Alle Facturen',
    'invoice_number': 'Factuur #',
    'client_information': 'Klantinformatie',
    'select_client': 'Selecteer Klant',
    'line_items': 'Artikelen',
    'profile_created': 'Nieuw profiel succesvol aangemaakt',
    'profile_updated': 'Profiel succesvol bijgewerkt',
    'failed_to_fetch_profile_data': 'Kan profielgegevens niet ophalen',
    'failed_to_create_profile': 'Kan geen nieuw profiel aanmaken',
    'failed_to_update_profile': 'Kan profiel niet bijwerken',
    'business_settings_updated': 'Bedrijfsinstellingen succesvol bijgewerkt',
    'failed_to_fetch_business_data': 'Kan bedrijfsgegevens niet ophalen',
    'failed_to_update_business_settings': 'Kan bedrijfsinstellingen niet bijwerken',
    'notes_attachments': 'Notities & Bijlagen',
    'payment_information': 'Betalingsinformatie',
    'payment_terms': 'Betalingsvoorwaarden',
    'po_number': 'PO Nummer',
    'qty': 'Aantal',
    'quantity': 'Aantal',
    'unit_price': 'Eenheidsprijs',
    'unit_type': 'Eenheidstype',
    'vat_rate': 'BTW Tarief',
    'vat_percent': 'BTW %',
    'discount': 'Korting',
    'subtotal': 'Subtotaal',
    'total': 'Totaal',
    'save_invoice': 'Factuur Opslaan',
    'create_invoice': 'Factuur Aanmaken',
    'update_invoice': 'Factuur Bijwerken',
    
    // Auth
    'auth.login.success': 'Inloggen Succesvol',
    'auth.welcome.back': 'Welkom terug bij InvoiceFlow Genius!',
    'auth.login.failed': 'Inloggen Mislukt',
    'auth.check.credentials': 'Inloggen mislukt. Controleer uw gegevens en probeer het opnieuw.',
    'auth.signup.success': 'Registratie Succesvol',
    'auth.verify.email': 'Welkom bij InvoiceFlow Genius! Controleer uw e-mail om uw account te verifiëren.',
    'auth.signup.failed': 'Registratie Mislukt',
    'auth.try.again': 'Kon geen account aanmaken. Probeer het opnieuw.',
    'auth.have.account': 'Voer uw gegevens in om toegang te krijgen tot uw account',
    'auth.no.account': 'Maak een nieuw account aan om te beginnen',
    'auth.login': 'Inloggen',
    'auth.register': 'Registreren',
    'auth.email': 'E-mail',
    'auth.email.placeholder': 'uw.email@voorbeeld.com',
    'auth.password': 'Wachtwoord',
    'auth.confirm.password': 'Bevestig Wachtwoord',
    'auth.logging.in': 'Inloggen...',
    'auth.creating.account': 'Account aanmaken...',
    'auth.password.mismatch': 'Wachtwoorden komen niet overeen',
    'auth.password.length': 'Wachtwoord moet minimaal 6 tekens bevatten',
    'auth.terms.agreement': 'Door verder te gaan, gaat u akkoord met onze Servicevoorwaarden en Privacybeleid.',
    
    // Navigation and sections
    'clients.title': 'Klanten',
    'invoices.title': 'Facturen',
    'quotes.title': 'Offertes',
    'settings.title': 'Instellingen',
    'invoices': 'Facturen',
    'due_date': 'Vervaldatum',
    'client': 'Klant',
    'amount': 'Bedrag',
    'status': 'Status',
    'actions': 'Acties',
    'search_invoices': 'Zoek facturen...',
    'loading_invoices': 'Facturen laden...',
    'no_invoices_match_search': 'Geen facturen komen overeen met uw zoekopdracht',
    'no_invoices_found': 'Geen facturen gevonden. Maak uw eerste factuur!',
    'download_pdf': 'PDF Downloaden',
    'send_email': 'E-mail Versturen',
    'email': 'E-mail',
    'cancel_via_credit_note': 'Annuleren via creditnota',
    'duplicate': 'Dupliceren',
    'delete_invoice': 'Factuur Verwijderen',
    'delete_invoice_confirmation': 'Weet u zeker dat u factuur wilt verwijderen',
    'this_action_cannot_be_undone': 'Deze actie kan niet ongedaan worden gemaakt.',
    'deleting': 'Verwijderen...',
    'invoice_deleted': 'Factuur Verwijderd',
    'invoice_deleted_description': 'De factuur is succesvol verwijderd.',
    'failed_to_delete_invoice': 'Kan factuur niet verwijderen',
    'invoice_updated': 'Factuur Bijgewerkt',
    'invoice_status_updated': 'De factuurstatus is bijgewerkt.',
    'failed_to_update_invoice_status': 'Kan factuurstatus niet bijwerken',
    'invoice_duplicated': 'Factuur Gedupliceerd',
    'invoice_duplicated_description': 'Een kopie van de factuur is gemaakt.',
    'failed_to_duplicate_invoice': 'Kan factuur niet dupliceren',
    'email_sent': 'E-mail Verzonden',
    'email_sent_description': 'De factuur is per e-mail verzonden naar',
    'generating_pdf': 'PDF Genereren',
    'generating_pdf_description': 'Uw factuur-PDF wordt voorbereid voor downloaden.',
    'date': 'Datum',
    
    // Quotes
    'quotes.add': 'Offerte Toevoegen',
    'quotes.all': 'Alle Offertes',
    'quotes.search': 'Zoek offertes...',
    'quotes.none_found': 'Geen offertes gevonden. Maak uw eerste offerte!',
    'quotes.no_match_search': 'Geen offertes komen overeen met uw zoekopdracht',
    'quotes.number': 'Offerte #',
    'quotes.expiry_date': 'Vervaldatum',
    'quotes.cancel': 'Offerte Annuleren',
    'quotes.delete': 'Offerte Verwijderen',
    'quotes.confirm_delete': 'Weet u zeker dat u offerte wilt verwijderen',
    
    // Settings
    'settings.billing': 'Facturering & Abonnement',
    'settings.billing.manage': 'Beheer uw factureringsinformatie en abonnementsgegevens',
    'settings.billing.current.plan': 'Huidig Abonnement',
    'settings.billing.payment.methods': 'Betaalmethoden',
    'settings.billing.no.payment.methods': 'U heeft nog geen betaalmethoden toegevoegd.',
    'settings.billing.add.payment': 'Betaalmethode Toevoegen',
    
    // Dashboard
    'dashboard.recent.activity': 'Recente Activiteit',
    'dashboard.invoice.overview': 'Factuur Overzicht',
    
    // Pricing
    'pricing.free': 'Gratis',
    'pricing.yearly': 'Jaarlijks',
    'pricing.monthly': 'Maandelijks',
    'pricing.save.up.to': 'Bespaar tot 20%',
    'pricing.starter': 'Starter',
    'pricing.standard': 'Standaard',
    'pricing.pro': 'Pro',
    'pricing.per.month': 'per maand',
    'pricing.month': 'maand',
    'pricing.promo.starter': 'Promotie voor kleine starters',
    'pricing.most.popular': 'Populairste optie',
    'pricing.good.for.active': 'Goed voor draaiende activiteiten',
    'pricing.free.trial': 'Gratis proefabonnement',
    'pricing.tax.deductible': '100% aftrekbaar!',
    'pricing.invoices.per.quarter': 'facturen / kwartaal',
    'pricing.quotes.per.quarter': 'offertes / kwartaal',
    'pricing.free.access': 'Gratis Peppol toegang',
    'pricing.unlimited.users': 'Onbeperkt aantal gebruiker',
    'pricing.user': 'gebruiker',
    'pricing.all.prices': '*Alle prijzen excl. 21% BTW.',
    'pricing.custom.price': 'Voor bedrijven met meer dan 900 facturen per kwartaal maken wij een gepersonaliseerde prijs.',
    'pricing.simple.transparent': 'Eenvoudige, Transparante Prijzen',
    'pricing.choose.plan': 'Kies het abonnement dat het beste bij uw bedrijf past',
    'pricing.individuals.small': 'Voor particulieren en kleine bedrijven',
    'pricing.growing.businesses': 'Voor groeiende bedrijven',
    'pricing.companies.teams': 'Voor bedrijven en teams',
    'pricing.unlimited.invoices': 'Onbeperkt facturen',
    'pricing.unlimited.clients': 'Onbeperkt klanten',
    'pricing.pdf.export': 'PDF Export',
    'pricing.email.invoices': 'E-mail facturen',
    'pricing.basic.analytics': 'Basis analyses',
    'pricing.advanced.analytics': 'Geavanceerde analyses',
    'pricing.email.support': 'E-mail ondersteuning',
    'pricing.priority.support': 'Prioriteit ondersteuning',
    'pricing.custom.branding': 'Aangepaste branding',
    'pricing.multiple.users': 'Meerdere gebruikers',
    'pricing.get.started': 'Aan de slag',
    'pricing.subscribe.now': 'Nu abonneren',
    'pricing.contact.sales': 'Contact verkoop',
    'pricing.business': 'Zakelijk',
    
    // Settings continued
    'settings.company': 'Bedrijf',
    'settings.profile': 'Profiel',
    'settings.users': 'Gebruikers',
    'settings.general': 'Algemeen',
    'settings.localization': 'Lokalisatie',
    'settings.email_settings': 'E-mailinstellingen',
    'settings.integrations': 'Integraties',
    'settings.customize_look': 'Uiterlijk aanpassen',
    'settings.security': 'Beveiliging',
    'settings.api': 'API',
    'settings.developers': 'Ontwikkelaars',
    'settings.advanced': 'Geavanceerd',
    'settings.my_profile': 'Mijn profiel',
    'settings.edit_profile': 'Profiel bewerken',
    'settings.change_password': 'Wachtwoord wijzigen',
    'settings.notifications': 'Meldingen',
    'settings.account_settings': 'Accountinstellingen',
    'settings.plan_details': 'Abonnementsdetails',
    'settings.usage': 'Gebruik',
    'settings.invoices_and_billing': 'Facturen en facturering',
    'settings.payment_methods': 'Betaalmethoden',
    'settings.cancel_subscription': 'Abonnement opzeggen',
    'settings.company_profile': 'Bedrijfsprofiel',
    'settings.business_details': 'Bedrijfsgegevens',
    'settings.tax_information': 'Belastinginformatie',
    'settings.financial_details': 'Financiële gegevens',
    'settings.email_templates': 'E-mailsjablonen',
    'settings.invoice_settings': 'Factuurinstellingen',
    'settings.quote_settings': 'Offerte-instellingen',
    'settings.api_keys': 'API-sleutels',
    'settings.webhooks': 'Webhooks',
    'settings.audit_log': 'Auditlogboek',
    'settings.data_export': 'Gegevens exporteren',
    'settings.gdpr_compliance': 'AVG-naleving',
    'settings.terms_of_service': 'Servicevoorwaarden',
    'settings.privacy_policy': 'Privacybeleid',
    'settings.cookie_policy': 'Cookiebeleid',
    'settings.licenses': 'Licenties',
    'settings.third_party_licenses': 'Licenties van derden',
    'settings.version': 'Versie',
    'settings.release_notes': 'Release-opmerkingen',
    'settings.support': 'Ondersteuning',
    'settings.documentation': 'Documentatie',
    'settings.community_forum': 'Communityforum',
    'settings.tutorials': 'Tutorials',
    'settings.faq': 'FAQ',
    'settings.contact_us': 'Neem contact met ons op',
    'settings.feedback': 'Feedback',
    'settings.report_a_bug': 'Meld een bug',
    'settings.request_a_feature': 'Functie aanvragen',
    'settings.keyboard_shortcuts': 'Sneltoetsen',
    'settings.accessibility': 'Toegankelijkheid',
    'settings.dark_mode': 'Donkere modus',
    'settings.language': 'Taal',
    'settings.time_zone': 'Tijdzone',
    'settings.date_format': 'Datumnotatie',
    'settings.currency': 'Valuta',
    'settings.country': 'Land',
    'settings.address': 'Adres',
    'settings.city': 'Stad',
    'settings.state': 'Provincie',
    'settings.zip_code': 'Postcode',
    'settings.phone': 'Telefoon',
    'settings.website': 'Website',
    'settings.logo': 'Logo',
    'settings.social_media': 'Sociale media',
    'settings.facebook': 'Facebook',
    'settings.twitter': 'Twitter',
    'settings.linkedin': 'LinkedIn',
    'settings.instagram': 'Instagram',
    'settings.youtube': 'YouTube',
    'settings.skype': 'Skype',
    'settings.slack': 'Slack',
    'settings.discord': 'Discord',
    'settings.telegram': 'Telegram',
    'settings.whatsapp': 'WhatsApp',
    'settings.wechat': 'WeChat',
    'settings.qq': 'QQ',
    'settings.weibo': 'Weibo',
    'settings.vk': 'VK',
    'settings.odnoklassniki': 'Odnoklassniki',
    'settings.tumblr': 'Tumblr',
    'settings.pinterest': 'Pinterest',
    'settings.flickr': 'Flickr',
    'settings.dribbble': 'Dribbble',
    'settings.behance': 'Behance',
    'settings.medium': 'Medium',
    'settings.github': 'GitHub',
    'settings.gitlab': 'GitLab',
    'settings.bitbucket': 'Bitbucket',
    'settings.stackoverflow': 'Stack Overflow',
    'settings.quora': 'Quora',
    'settings.reddit': 'Reddit',
    'settings.hacker_news': 'Hacker News',
    'settings.product_hunt': 'Product Hunt',
    'settings.crunchbase': 'Crunchbase',
    'settings.angelist': 'AngelList',
    'settings.glassdoor': 'Glassdoor',
    'settings.indeed': 'Indeed',
    'settings.monster': 'Monster',
    'settings.careerbuilder': 'CareerBuilder',
    'settings.dice': 'Dice',
    'settings.linkedin_jobs': 'LinkedIn Jobs',
    'settings.indeed_jobs': 'Indeed Jobs',
    'settings.monster_jobs': 'Monster Jobs',
    'settings.careerbuilder_jobs': 'CareerBuilder Jobs',
    'settings.dice_jobs': 'Dice Jobs',
    'settings.google_jobs': 'Google Jobs',
    'settings.bing_jobs': 'Bing Jobs',
    'settings.yahoo_jobs': 'Yahoo Jobs',
  },
  fr: {
    // Common
    'app.name': 'InvoiceFlow Genius',
    'login': 'Connexion',
    'register': 'S\'inscrire',
    'logout': 'Déconnexion',
    'free.version': 'Version Gratuite',
    'contact': 'Contact',
    'pricing': 'Prix',
    'loading': 'Chargement...',
    'view.all': 'Voir Tout',
    'dashboard': 'Tableau de bord',
    'welcome.back': 'Bienvenue sur votre tableau de bord',
    'error': 'Erreur',
    'success': 'Succès',
    'total.invoices': 'Total des Factures',
    'pending.amount': 'Montant en Attente',
    'total.clients': 'Total des Clients',
    'revenue.growth': 'Croissance des Revenus',
    'from.last.month': 'par rapport au mois précédent',
    'new.this.month': 'nouveaux ce mois-ci',
    'year.over.year': 'année après année',
    'increase': 'augmentation',
    'decrease': 'diminution',
    'create': 'Créer',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'search': 'Rechercher',
    'all_invoices': 'Toutes les Factures',
    'invoice_number': 'Facture #',
    'client_information': 'Informations Client',
    'select_client': 'Sélectionner Client',
    'line_items': 'Articles',
    'profile_created': 'Nouveau profil créé avec succès',
    'profile_updated': 'Profil mis à jour avec succès',
    'failed_to_fetch_profile_data': 'Échec de la récupération des données de profil',
    'failed_to_create_profile': 'Échec de la création du nouveau profil',
    'failed_to_update_profile': 'Échec de la mise à jour du profil',
    'business_settings_updated': 'Paramètres d\'entreprise mis à jour avec succès',
    'failed_to_fetch_business_data': 'Échec de la récupération des données d\'entreprise',
    'failed_to_update_business_settings': 'Échec de la mise à jour des paramètres d\'entreprise',
    'notes_attachments': 'Notes & Pièces jointes',
    'payment_information': 'Informations de paiement',
    'payment_terms': 'Conditions de paiement',
    'po_number': 'Numéro de commande',
    'qty': 'Quantité',
    'quantity': 'Quantité',
    'unit_price': 'Prix unitaire',
    'unit_type': 'Type d\'unité',
    'vat_rate': 'Taux de TVA',
    'vat_percent': 'TVA %',
    'discount': 'Remise',
    'subtotal': 'Sous-total',
    'total': 'Total',
    'save_invoice': 'Enregistrer la facture',
    'create_invoice': 'Créer une facture',
    'update_invoice': 'Mettre à jour la facture',
    
    // Auth
    'auth.login.success': 'Connexion réussie',
    'auth.welcome.back': 'Bienvenue sur InvoiceFlow Genius!',
    'auth.login.failed': 'Échec de connexion',
    'auth.check.credentials': 'Échec de la connexion. Veuillez vérifier vos identifiants et réessayer.',
    'auth.signup.success': 'Inscription réussie',
    'auth.verify.email': 'Bienvenue sur InvoiceFlow Genius ! Veuillez vérifier votre e-mail pour confirmer votre compte.',
    'auth.signup.failed': 'Échec de l\'inscription',
    'auth.try.again': 'Impossible de créer un compte. Veuillez réessayer.',
    'auth.have.account': 'Entrez vos identifiants pour accéder à votre compte',
    'auth.no.account': 'Créez un nouveau compte pour commencer',
    'auth.login': 'Connexion',
    'auth.register': 'S\'inscrire',
    'auth.email': 'E-mail',
    'auth.email.placeholder': 'votre.email@exemple.com',
    'auth.password': 'Mot de passe',
    'auth.confirm.password': 'Confirmer le mot de passe',
    'auth.logging.in': 'Connexion en cours...',
    'auth.creating.account': 'Création du compte...',
    'auth.password.mismatch': 'Les mots de passe ne correspondent pas',
    'auth.password.length': 'Le mot de passe doit comporter au moins 6 caractères',
    'auth.terms.agreement': 'En continuant, vous acceptez nos Conditions d\'utilisation et notre Politique de confidentialité.',
    
    // Navigation and sections
    'clients.title': 'Clients',
    'invoices.title': 'Factures',
    'quotes.title': 'Devis',
    'settings.title': 'Paramètres',
    'invoices': 'Factures',
    'due_date': 'Date d\'échéance',
    'client': 'Client',
    'amount': 'Montant',
    'status': 'Statut',
    'actions': 'Actions',
    'search_invoices': 'Rechercher des factures...',
    'loading_invoices': 'Chargement des factures...',
    'no_invoices_match_search': 'Aucune facture ne correspond à votre recherche',
    'no_invoices_found': 'Aucune facture trouvée. Créez votre première facture!',
    'download_pdf': 'Télécharger PDF',
    'send_email': 'Envoyer par e-mail',
    'email': 'E-mail',
    'cancel_via_credit_note': 'Annuler via un avoir',
    'duplicate': 'Dupliquer',
    'delete_invoice': 'Supprimer la facture',
    'delete_invoice_confirmation': 'Êtes-vous sûr de vouloir supprimer la facture',
    'this_action_cannot_be_undone': 'Cette action ne peut pas être annulée.',
    'deleting': 'Suppression...',
    'invoice_deleted': 'Facture supprimée',
    'invoice_deleted_description': 'La facture a été supprimée avec succès.',
    'failed_to_delete_invoice': 'Échec de la suppression de la facture',
    'invoice_updated': 'Facture mise à jour',
    'invoice_status_updated': 'Le statut de la facture a été mis à jour.',
    'failed_to_update_invoice_status': 'Échec de la mise à jour du statut de la facture',
    'invoice_duplicated': 'Facture dupliquée',
    'invoice_duplicated_description': 'Une copie de la facture a été créée.',
    'failed_to_duplicate_invoice': 'Échec de la duplication de la facture',
    'email_sent': 'E-mail envoyé',
    'email_sent_description': 'La facture a été envoyée par e-mail à',
    'generating_pdf': 'Génération du PDF',
    'generating_pdf_description': 'Votre PDF de facture est en cours de préparation pour le téléchargement.',
    'date': 'Date',
    
    // Quotes
    'quotes.add': 'Ajouter un devis',
    'quotes.all': 'Tous les devis',
    'quotes.search': 'Rechercher des devis...',
    'quotes.none_found': 'Aucun devis trouvé. Créez votre premier devis!',
    'quotes.no_match_search': 'Aucun devis ne correspond à votre recherche',
    'quotes.number': 'Devis #',
    'quotes.expiry_date': 'Date d\'expiration',
    'quotes.cancel': 'Annuler le devis',
    'quotes.delete': 'Supprimer le devis',
    'quotes.confirm_delete': 'Êtes-vous sûr de vouloir supprimer le devis',
    
    // Settings
    'settings.billing': 'Facturation & Abonnement',
    'settings.billing.manage': 'Gérez vos informations de facturation et les détails de votre abonnement',
    'settings.billing.current.plan': 'Plan actuel',
    'settings.billing.payment.methods': 'Moyens de paiement',
    'settings.billing.no.payment.methods': 'Vous n\'avez pas encore ajouté de moyens de paiement.',
    'settings.billing.add.payment': 'Ajouter un moyen de paiement',
    
    // Dashboard
    'dashboard.recent.activity': 'Activité récente',
    'dashboard.invoice.overview': 'Aperçu des factures',
    
    // Pricing
    'pricing.free': 'Gratuit',
    'pricing.yearly': 'Annuel',
    'pricing.monthly': 'Mensuel',
    'pricing.save.up.to': 'Économisez jusqu\'à 20%',
    'pricing.starter': 'Débutant',
    'pricing.standard': 'Standard',
    'pricing.pro': 'Pro',
    'pricing.per.month': 'par mois',
    'pricing.month': 'mois',
    'pricing.promo.starter': 'Promotion pour petits débutants',
    'pricing.most.popular': 'Option la plus populaire',
    'pricing.good.for.active': 'Bon pour une activité soutenue',
    'pricing.free.trial': 'Essai gratuit',
    'pricing.tax.deductible': '100% déductible!',
    'pricing.invoices.per.quarter': 'factures / trimestre',
    'pricing.quotes.per.quarter': 'devis / trimestre',
    'pricing.free.access': 'Accès gratuit',
    'pricing.unlimited.users': 'Utilisateurs illimités',
    'pricing.user': 'utilisateur',
    'pricing.all.prices': '*Tous les prix hors TVA 21%.',
    'pricing.custom.price': 'Pour les entreprises avec plus de 900 factures par trimestre, nous proposons un prix personnalisé.',
    'pricing.simple.transparent': 'Prix simple et transparent',
    'pricing.choose.plan': 'Choisissez le plan qui convient le mieux à votre entreprise',
    'pricing.individuals.small': 'Pour particuliers et petites entreprises',
    'pricing.growing.businesses': 'Pour entreprises en croissance',
    'pricing.companies.teams': 'Pour entreprises et équipes',
    'pricing.unlimited.invoices': 'Factures illimitées',
    'pricing.unlimited.clients': 'Clients illimités',
    'pricing.pdf.export': 'Export PDF',
    'pricing.email.invoices': 'Factures par e-mail',
    'pricing.basic.analytics': 'Analyses de base',
    'pricing.advanced.analytics': 'Analyses avancées',
    'pricing.email.support': 'Support par e-mail',
    'pricing.priority.support': 'Support prioritaire',
    'pricing.custom.branding': 'Personnalisation de marque',
    'pricing.multiple.users': 'Utilisateurs multiples',
    'pricing.get.started': 'Commencer',
    'pricing.subscribe.now': 'S\'abonner maintenant',
    'pricing.contact.sales': 'Contacter les ventes',
    'pricing.business': 'Entreprise',
    
    // Settings continued
    'settings.company': 'Entreprise',
    'settings.profile': 'Profil',
    'settings.users': 'Utilisateurs',
    'settings.general': 'Général',
    'settings.localization': 'Localisation',
    'settings.email_settings': 'Paramètres e-mail',
    'settings.integrations': 'Intégrations',
    'settings.customize_look': 'Personnaliser l\'apparence',
    'settings.security': 'Sécurité',
    'settings.api': 'API',
    'settings.developers': 'Développeurs',
    'settings.advanced': 'Avancé',
    'settings.my_profile': 'Mon profil',
    'settings.edit_profile': 'Modifier le profil',
    'settings.change_password': 'Changer le mot de passe',
    'settings.notifications': 'Notifications',
    'settings.account_settings': 'Paramètres du compte',
    'settings.plan_details': 'Détails du plan',
    'settings.usage': 'Utilisation',
    'settings.invoices_and_billing': 'Factures et facturation',
    'settings.payment_methods': 'Moyens de paiement',
    'settings.cancel_subscription': 'Annuler l\'abonnement',
    'settings.company_profile': 'Profil d\'entreprise',
    'settings.business_details': 'Détails de l\'entreprise',
    'settings.tax_information': 'Informations fiscales',
    'settings.financial_details': 'Détails financiers',
    'settings.email_templates': 'Modèles d\'e-mail',
    'settings.invoice_settings': 'Paramètres de facture',
    'settings.quote_settings': 'Paramètres de devis',
    'settings.api_keys': 'Clés API',
    'settings.webhooks': 'Webhooks',
    'settings.audit_log': 'Journal d\'audit',
    'settings.data_export': 'Exportation de données',
    'settings.gdpr_compliance': 'Conformité RGPD',
    'settings.terms_of_service': 'Conditions d\'utilisation',
    'settings.privacy_policy': 'Politique de confidentialité',
    'settings.cookie_policy': 'Politique de cookies',
    'settings.licenses': 'Licences',
    'settings.third_party_licenses': 'Licences tierces',
    'settings.version': 'Version',
    'settings.release_notes': 'Notes de version',
    'settings.support': 'Support',
    'settings.documentation': 'Documentation',
    'settings.community_forum': 'Forum communautaire',
    'settings.tutorials': 'Tutoriels',
    'settings.faq': 'FAQ',
    'settings.contact_us': 'Contactez-nous',
    'settings.feedback': 'Commentaires',
    'settings.report_a_bug': 'Signaler un bug',
    'settings.request_a_feature': 'Demander une fonctionnalité',
    'settings.keyboard_shortcuts': 'Raccourcis clavier',
    'settings.accessibility': 'Accessibilité',
    'settings.dark_mode': 'Mode sombre',
    'settings.language': 'Langue',
    'settings.time_zone': 'Fuseau horaire',
    'settings.date_format': 'Format de date',
    'settings.currency': 'Devise',
    'settings.country': 'Pays',
    'settings.address': 'Adresse',
    'settings.city': 'Ville',
    'settings.state': 'État/Région',
    'settings.zip_code': 'Code postal',
    'settings.phone': 'Téléphone',
    'settings.website': 'Site web',
    'settings.logo': 'Logo',
    'settings.social_media': 'Médias sociaux',
    'settings.facebook': 'Facebook',
    'settings.twitter': 'Twitter',
    'settings.linkedin': 'LinkedIn',
    'settings.instagram': 'Instagram',
    'settings.youtube': 'YouTube',
    'settings.skype': 'Skype',
    'settings.slack': 'Slack',
    'settings.discord': 'Discord',
    'settings.telegram': 'Telegram',
    'settings.whatsapp': 'WhatsApp',
    'settings.wechat': 'WeChat',
    'settings.qq': 'QQ',
    'settings.weibo': 'Weibo',
    'settings.vk': 'VK',
    'settings.odnoklassniki': 'Odnoklassniki',
    'settings.tumblr': 'Tumblr',
    'settings.pinterest': 'Pinterest',
    'settings.flickr': 'Flickr',
    'settings.dribbble': 'Dribbble',
    'settings.behance': 'Behance',
    'settings.medium': 'Medium',
    'settings.github': 'GitHub',
    'settings.gitlab': 'GitLab',
    'settings.bitbucket': 'Bitbucket',
    'settings.stackoverflow': 'Stack Overflow',
    'settings.quora': 'Quora',
    'settings.reddit': 'Reddit',
    'settings.hacker_news': 'Hacker News',
    'settings.product_hunt': 'Product Hunt',
    'settings.crunchbase': 'Crunchbase',
    'settings.angelist': 'AngelList',
    'settings.glassdoor': 'Glassdoor',
    'settings.indeed': 'Indeed',
    'settings.monster': 'Monster',
    'settings.careerbuilder': 'CareerBuilder',
    'settings.dice': 'Dice',
    'settings.linkedin_jobs': 'LinkedIn Jobs',
    'settings.indeed_jobs': 'Indeed Jobs',
    'settings.monster_jobs': 'Monster Jobs',
    'settings.careerbuilder_jobs': 'CareerBuilder Jobs',
    'settings.dice_jobs': 'Dice Jobs',
    'settings.google_jobs': 'Google Jobs',
    'settings.bing_jobs': 'Bing Jobs',
    'settings.yahoo_jobs': 'Yahoo Jobs'
  }
};

const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Get from localStorage or use default
    const savedLanguage = localStorage.getItem('language');
    return (savedLanguage as Language) || defaultLanguage;
  });
  
  useEffect(() => {
    // Save to localStorage
    localStorage.setItem('language', language);
    
    // Dispatch event to notify components that language has changed
    window.dispatchEvent(new Event('language-changed'));
    
    // Set HTML lang attribute
    document.documentElement.setAttribute('lang', language);
  }, [language]);
  
  const t = (key: string): string => {
    if (translations[language]?.[key]) {
      return translations[language][key];
    }
    
    // Fallback to English if the key doesn't exist in the current language
    if (translations['en']?.[key]) {
      return translations['en'][key];
    }
    
    // If all else fails, return the key itself
    return key;
  };
  
  const value = {
    language,
    setLanguage,
    t
  };
  
  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { LanguageProvider, useLanguage };
